name: CI/CD

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint


  build-docker-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: ci

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build . -t ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):$(echo $GITHUB_REF | sed 's/refs\/tags\///')

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):$(echo $GITHUB_REF | sed 's/refs\/tags\///')

    - name: Create Docker image latest
      run: docker tag ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):$(echo $GITHUB_REF | sed 's/refs\/tags\///') ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):latest

    - name: Push Docker image latest
      run: docker push ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Copy SSH key
      uses: appleboy/ssh-action@v0.1.4
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.REMOTE_HOST }}
        username: root
        port: 22
        script: |
          cd /root/deployment
          docker compose pull
          docker compose up -d --build