name: CI & Deploy to Test

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint


  build-docker-image:
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      packages: 'read'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL_TEST }} -t ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):$GITHUB_SHA .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):$GITHUB_SHA

      - name: Create Docker image latest test
        run: docker tag ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):$GITHUB_SHA ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):latest-test

      - name: Push Docker image latest test
        run: docker push ghcr.io/${{ github.repository_owner }}/$(basename $GITHUB_REPOSITORY):latest-test

  deploy-to-gcp-test:
      runs-on: ubuntu-latest
      needs: build-docker-image
      permissions:
        contents: 'read'
        id-token: 'write'
        packages: 'read' 

      steps:
      - uses: 'actions/checkout@v4'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: 'production-instance'
          user: '${{ secrets.REMOTE_USER }}'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          zone: 'us-central1-f'
          command: "echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin && \
            docker pull ghcr.io/proyecto-arima/webapp:latest-test && \
            cd .. && \
            cd ${{ secrets.REMOTE_PATH }} && \
            docker compose --profile webapp down && \
            docker compose --profile webapp up -d --build"
      
      - id: 'output'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
